---
- hosts: all
  vars:
    - i3_use_gaps: false
    - i3_terminal: xfce4-terminal
    - i3_use_polybar: false
  remote_user: root
  tasks:
  - name: Install missing packages
    apt:
      pkg:
        - i3-wm
        - i3lock
        - i3status
        - zsh
        - neovim
        - apt-file
        - nodejs
      state: latest
      update_cache: yes
  - name: Set shell of user root to zsh
    user:
      name: root
      shell: /bin/zsh
  roles:
     - ansible-xresources
     - ansible-i3
     - ansible-vim
     - ansible-xfce4-terminal
     - ansible-tmux
     - ansible-zsh
     - ansible-rofi
